"""Add current_date to games

Revision ID: 5e6012dc0e16
Revises: 001_initial
Create Date: 2026-03-08 13:03:37.836923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6012dc0e16'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commander_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('turn_issued', sa.Integer(), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('roe', sa.Text(), nullable=True),
    sa.Column('priorities', sa.JSON(), nullable=True),
    sa.Column('time_limit', sa.String(), nullable=True),
    sa.Column('available_forces', sa.JSON(), nullable=True),
    sa.Column('reporting_requirements', sa.JSON(), nullable=True),
    sa.Column('last_reported', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['commander_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commander_orders_id'), 'commander_orders', ['id'], unique=False)
    op.add_column('games', sa.Column('current_date', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('order_level', sa.Enum('TACTICAL', 'OPERATIONAL', 'STRATEGIC', name='orderlevel'), nullable=True))
    op.add_column('units', sa.Column('interceptors', sa.Integer(), nullable=True))
    op.add_column('units', sa.Column('precision_munitions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'precision_munitions')
    op.drop_column('units', 'interceptors')
    op.drop_column('orders', 'order_level')
    op.drop_column('games', 'current_date')
    op.drop_index(op.f('ix_commander_orders_id'), table_name='commander_orders')
    op.drop_table('commander_orders')
    # ### end Alembic commands ###
